
# eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763


#jpa config
spring:
  application:
    name: order-client
  rabbitmq:
    addresses: 10.1.51.96
    host: 10.1.51.96
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    template:
      reply-timeout: 1000
  redis:
    database: 0
    host: 10.1.51.96
    password: redis
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 1000

